### ISSUE TITLE
Add the timer on the title of the page...

### ISSUE THREAD

**Issue by iagodahlem** [iagodahlem/tiempo#15]
... so the user can easily see the current timer without switching to the app page.

[React Helmet](https://github.com/nfl/react-helmet) can be used to achieve this.

Think on a format to display it, maybe using the current entry type (pomodoro, short-break, long-break) and the timer, or just the timer, currently it's just showing `Tiempo`, examples:

Showing the type first and the lapse:
- `Pomodoro | 24:59`
- `Short Break | 4:56`

Also think in a good place to fit it, where does not affect the performance of the app.

**Comment by jprask** [comment]
Hey, how is it going ?

Perhaps there could be a stand-alone component for that since it's going to receive new props every second, and we could put it in `src/index.js`, something like...
```
ReactDOM.render((
  <Provider store={store}>
    <App>
      <PomodoroHelmet/>
      <PomodoroPage />
    </App>
  </Provider>
), document.getElementById('root'))
```
What do you think ?

cool app :+1:

**Comment by iagodahlem** [comment]
Yo! 

Thanks, man! Appreciate any help.

Yeah, that's pretty much what I have thought, I would just put it inside the `PomodoroPage` component, this way we keep everything related to pomodoro inside the pomodoro page itself.

I think it's better to call the pomodoro helmet component something like `PomodoroHead`, I usually try to avoid naming things according to the library that is being used, this can lead into some coupling issues.

This `PomodoroHead` component can be connected to get the `lapse` and `title` to pass to the `Helmet` component, you can use a `format` function that is already being used on the `PomodoroLapse` to format the `lapse` timestamp.

**Comment by jprask** [comment]
Nice, good input.

I will give it a try!
